service: boda-photo-scrapper
provider:
  name: aws
  runtime: nodejs6.10
  timeout: 300
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"
functions:
  scrap:
    handler: index.Scrap
    environment:
        TWITTER_APP_CONSUMER_KEY: ${env:TWITTER_APP_CONSUMER_KEY, file(env.yml):TWITTER_APP_CONSUMER_KEY}
        TWITTER_APP_SECRET: ${env:TWITTER_APP_SECRET, file(env.yml):TWITTER_APP_SECRET}
        TWITTER_APP_ACT: ${env:TWITTER_APP_ACT, file(env.yml):TWITTER_APP_ACT}
        TWITTER_APP_ACT_SECRET: ${env:TWITTER_APP_ACT_SECRET, file(env.yml):TWITTER_APP_ACT_SECRET}
        HASHTAG: ${env:HASHTAG, file(env.yml):HASHTAG}
        S3_BUCKET: ${env:S3_BUCKET, file(env.yml):S3_BUCKET}-${opt:stage, "dev"}
    events:
        - schedule:
            rate: rate(60 minutes)
            enabled: true
resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:S3_BUCKET, file(env.yml):S3_BUCKET}-${opt:stage, "dev"}
plugins:
  - serverless-mocha-plugin
  - serverless-webpack
  - serverless-plugin-dotenv
